kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
  event:
    - push
    - custom

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: rust:latest
  commands:
    - cd impls/rust
    - cargo test --workspace
    - cargo test --workspace --release
- name: build
  image: rust:latest
  commands:
    - cd impls/rust
    - cargo build --workspace
    - cargo build --workspace --release
