[package]
name = "kot"
version = "0.1.0-dev"
edition = "2021"
authors = ["harmless-tech"]
description = "A command runner"
readme = "README.md"
license = "MIT"
repository = "https://github.com/harmless-tech/kot"
categories = ["command-line-utilities", "development-tools"]
keywords = ["command-line", "task", "runner", "development", "utility"]
#rust-version = "1.70"
include = [
    "src/",
    "Cargo.lock",
    "Cargo.toml",
    "LICENSE",
    "README.md"
]

[dependencies]
#anyhow = "1.0.75"
num_cpus = "1.16.0"
rustc-hash = "1.1.0"

[features]
default = ["i64", "threads"]
# Use i64 as int type.
i64 = []
# Allow args and other things to be processed on a separate thread. (Max: 2)
threads = []

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.small]
inherits = "release"
opt-level = "s"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }.zip"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"

[package.metadata.binstall.overrides.aarch64-pc-windows-msvc]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }.zip"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"
